Webpage/Webpage/urls.py
from django.contrib import admin
from django.urls import path
from MicroscopyQuizz.views import home
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from MicroscopyQuizz.views import homeSignin
from MicroscopyQuizz.views import userSignUp
from MicroscopyQuizz.views import choiceQuizz
from MicroscopyQuizz.views import classment
from MicroscopyQuizz.views import MicroscopyQuizzPageCorrection
from django.contrib.auth import logout as django_logout
from MicroscopyQuizz.views import MicroscopyQuizzView
from MicroscopyQuizz.views import CellularComponentQuizzView
from MicroscopyQuizz.views import searchBarImages
from MicroscopyQuizz.views import autocompleteSearchBar
from MicroscopyQuizz.views import searchBarImagesResults
from MicroscopyQuizz.views import ComponentPageCorrection
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('MiniQuizz', home, name='MiniQuizz'),
    path("MiniQuizz/login", LoginView.as_view(), name='login'),
    path("MiniQuizz/SignUp", userSignUp, name= "SignUp"),
    path('MiniQuizz/SignedIn', homeSignin, name = "SignedIn"),
    path('MiniQuizz/QuizzChoice', choiceQuizz , name = "QuizzChoice"),
    path('MiniQuizz/Microscopy', MicroscopyQuizzView.as_view(), name = 'QuizzMicroscopy'), 
    path('MiniQuizz/Microscopy/Correction', MicroscopyQuizzPageCorrection, name = 'QuizzMicroscopyCorrection'),
    path('MiniQuizz/classment', classment, name = 'classment'),
    path('MiniQuizz/Component', CellularComponentQuizzView.as_view(), name='QuizzComponent'),
    path('MiniQuizz/Component/Correction', ComponentPageCorrection, name = 'QuizzComponentCorrection'),
    path('MiniQuizz/logout', LogoutView.as_view(), name='logout'),
    path('MiniQuizz/ImageSearch', searchBarImages, name="searchImages"),
    path('MiniQuizz/SearchImages', autocompleteSearchBar, name = 'autocompleteImageSearchBar'),
    path('MiniQuizz/ImageSearch/Results', searchBarImagesResults, name='searchImagesResults'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)




    

Webpage/MicroscopyQuizz/models.py
from django.db import models

# Create your models here.

''' Class: User
This class allows to initialise user table in the database'''

class User(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    username = models.CharField(max_length=30)
    mailAddress = models.EmailField()
    password = models.CharField(max_length=50)
    score = models.IntegerField(null=True)
    gameActive = models.IntegerField(null=True)


''' Class: Images
This class allows to initialise images table in the database'''



class Images(models.Model):
    image_id = models.IntegerField()
    image_name = models.IntegerField()
    description = models.TextField()
    microscopy = models.CharField(max_length=60)
    cell_type = models.CharField(max_length=60)
    component = models.CharField(max_length=60)
    doi = models.CharField(max_length=60)
    organism = models.CharField(max_length=60)
    url = models.CharField(max_length=60)


''' Class: Question
This class allows to initialise question table in the database'''



class Question(models.Model):
    question_id = models.IntegerField()
    question = models.CharField(max_length=60)
    category = models.CharField(max_length=60)
    imageField = models.CharField(max_length=60)
    points = models.IntegerField()
    n_answer = models.IntegerField()
    n_image = models.IntegerField()


''' Class: Answers
This class allows to initialise answers table in the database'''

class Answers(models.Model):
    answerId = models.IntegerField()
    questionId = models.IntegerField()
    answer = models.CharField(max_length=60)
    definition = models.TextField()


''' Class: AnswersToTheQuizz
This class allows to initialise answerstothequizz 
table in the database'''


class AnswerToTheQuizz(models.Model):
    usernamePlusQuestion = models.CharField(max_length=120)
    goodAnswerId = models.IntegerField()

Webpage/MicroscopyQuizz/forms.py
from django import forms
from MicroscopyQuizz.models import User
from MicroscopyQuizz.models import AnswerToTheQuizz
from MicroscopyQuizz.models import Answers
from MicroscopyQuizz.models import Images

''' Class: UserFormSignUp
This class allows to initialise formular to signUp'''

class UserFormSignUp(forms.ModelForm):
    class Meta: 
        model = User
        fields = ('name', 'surname', 
            'username', 'mailAddress', 
            'password',)


''' Class: QuizzFormMicroscopy
This class allows to initialise formular to Answer to the 
questions concerning Microscopy'''

class QuizzFormMicroscopy(forms.Form):
    choices = []
    answer = Answers.objects.filter(questionId = 1)
    
    for i in answer.all(): 
        choices.append((i.answer, i.answer))
    
    firstQuestion = forms.ChoiceField(choices = choices, widget = forms.RadioSelect)
    secondQuestion = forms.ChoiceField(choices = choices, widget = forms.RadioSelect)
    thirdQuestion = forms.ChoiceField(choices = choices, widget = forms.RadioSelect)
    fourthQuestion = forms.ChoiceField(choices = choices, widget = forms.RadioSelect)


''' Class: QuizzFormComponent
This class allows to initialise formular to Answer to the 
questions concerning Cellular Component'''


class QuizzFormComponent(forms.Form):
    choices = []
    answer = Answers.objects.filter(questionId = 2)
    
    for j in answer.all():
        choices.append((j.answer, j.answer))

    firstQuestion = forms.ChoiceField(choices = choices, widget = forms.RadioSelect)
    secondQuestion = forms.ChoiceField(choices = choices, widget = forms.RadioSelect)
    thirdQuestion = forms.ChoiceField(choices = choices, widget = forms.RadioSelect)
    fourthQuestion = forms.ChoiceField(choices = choices, widget = forms.RadioSelect)


''' Class: ImageSearchBar
This class allows to initialise the search bar in the aim to 
search pictures in the pictures gallery '''


class ImageSearchBar(forms.Form):
    searchBar = forms.CharField(max_length=200)



''' Class: ListBoxSearchBar
This class allows to initialise the list box next to the search bar
in the aim to select the item to autocomplete the search bar '''


class ListBoxSearchBar(forms.Form):
    columnNames = [field.name for field in Images._meta.get_fields()]
    choices = []
    choices.append(("", ""))
    for i in columnNames:
        choices.append((i, i))
    
    listbox = forms.CharField(widget = forms.Select(choices = choices))

Webpage/MicroscopyQuizz/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from MicroscopyQuizz.forms import UserFormSignUp
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from MicroscopyQuizz.models import Question, Images, AnswerToTheQuizz, Answers
from MicroscopyQuizz.models import User as UserDatabase
import random
from django.test import Client
from MicroscopyQuizz.forms import QuizzFormMicroscopy, QuizzFormComponent
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth import logout
from django.views import View
from MicroscopyQuizz.forms import ImageSearchBar
from MicroscopyQuizz.forms import ListBoxSearchBar
from django.http import JsonResponse

# Create your views here.

''' Method: home
    This method is used to give the homepage View'''

def home(request,):
    return render(request, "home/home.html")



''' Method: homeSignin
    This method is used to give the homepage view when the user 
    is connected to the website '''

@login_required
def homeSignin(request):
    score = UserDatabase.objects.get(username=request.user.username)
    score = score.score
    
    if (score == None): 
        score = 0
        
    return render(request, "home/homeSignedIn.html", {'score': score})



''' Method: choiceQuizz
    This method is used to give the view of the page 
    displaying the choice of questions type'''

def choiceQuizz(request,):
    score = UserDatabase.objects.get(username=request.user.username)
    score = score.score
    
    if (score == None):
        score = 0
    
    return render(request, "quizzTemplate/quizzChoicesTemplate.html", {'score': score})




''' Class: MicroscopyQuizzView
    This class is used to give the view of the page 
    displaying the questions concerning Microscopy'''



class MicroscopyQuizzView(View):
    form = QuizzFormMicroscopy

    def get(self, request):
    
        score = UserDatabase.objects.get(username=request.user.username)
        score = score.score
    
        if (score == None): 
            score = 0

        ## We increment the active game number of the user
        username = "{}".format(request.user.username)
        user = UserDatabase.objects.get(username = username)
    

        userGameActive = user.gameActive + 1
        user.gameActive = user.gameActive + 1
        user.save()
        request.session['userGameActive'] = userGameActive
    

        ## We extract the question concerning the microscopy

        question = Question.objects.get(category= 'microscopy')

        ## For each quizz, we ask to the user 10 questions
        ## So we creat a list with the number of questions

        listItems = range(0,4)
        
        ## Creations a dictionnary to store the URLs per 
        ## question
        
        dictionnaryURL = {}
        
        ## For each question

        for iterator in listItems:

            ## Initializing the list of URLs 
            ## For each question

            dictionnaryURL[iterator] = []

            microscopy = Answers.objects.filter(questionId=1)
            microscopy = microscopy.all()
            random_microscopy = random.choice(microscopy)
            microscopy = random_microscopy.answer

            answer = Answers.objects.get(answer= microscopy)
            userId = "{}_{}_{}".format(request.user.username, request.session['userGameActive'], iterator)
            userAnswer = AnswerToTheQuizz(usernamePlusQuestion = userId, goodAnswerId = answer.answerId)
            userAnswer.save()
            
            ## Creating a dictionnary to store the images
            ## And a list to store already used images

            dictionnary_images = {}
            used_images = []

            ## For the four pictures

            for iterator2 in range(0, 2):

                ## If the dictionnary of images is empty

                if (dictionnary_images == {}):

                    ## We take images whose the microscopy type
                    ## corresponds to our microscopy answer

                    images = Images.objects.filter(microscopy = microscopy)
                    images = images.all()

                    ## We choose a picture randomly in the database
                    ## And we add it to the dictionnary_images and 
                    ## to the used images 

                    random_choice = random.choice(images)
                    dictionnary_images[iterator2] = random_choice.url
                    used_images.append(random_choice.image_name)

                else:

                    ## If the dictionnary of images is not empty
                    ## We take images whose the microscopy type
                    ## corresponds to our microscopy answer
                    ## We choose a picture randomly in the database

                    images = Images.objects.filter(microscopy = microscopy)
                    images = images.all()
                    random_choice = random.choice(images)
                    
                    ## If the random picture corresponds to a already 
                    ## used picture, so, While the picture corresponds 
                    ## to a already used picture, we choose another p
                    ## picture

                    while(random_choice.image_name in used_images):
                        random_choice = random.choice(images)

                    ## And then, we add it to the dictionnary of images 
                    ## and to the used images

                    dictionnary_images[iterator2] = random_choice.url
                    used_images.append(random_choice.image_name)

            
            ## For all the elements in the dictionnary of pictures

            for iterator3 in dictionnary_images:

                ## We replace all the spaces by plus sign to get the URL of the picture
                ## And we append the URL to the URL dictionnary

                dictionnaryURL[iterator].append(dictionnary_images[iterator3]) 


        
        request.session['choiceQuestion'] = question.category
        request.session['question'] = question.question
        request.session['dictionnaryURL'] = dictionnaryURL


        return render(request, "quizzTemplate/quizzTemplateMicroscopy.html", {'choiceQuestion': request.session.get('choiceQuestion'),
            'question': request.session.get('question'), 'form': MicroscopyQuizzView.form, 'dictionnaryURL': request.session.get('dictionnaryURL'), 
            'score': score} )


    def post(self, request):

        score = UserDatabase.objects.get(username=request.user.username)
        score = score.score
    
        if (score == None): 
            score = 0

        form = MicroscopyQuizzView.form(request.POST)         

        if (form.is_valid()):
            
            list_answers = [form.cleaned_data['firstQuestion'],
            form.cleaned_data['secondQuestion'], 
            form.cleaned_data['thirdQuestion'], 
            form.cleaned_data['fourthQuestion']
            ]


            request.session['list_answers'] = list_answers

            list_answer_to_answer = []
            list_description_answer = []

            gainedScore = 0

            for iterator4 in range(0, 4):
                user = UserDatabase.objects.get(username = "{}".format(request.user.username))

                usernameComposed = request.user.username + "_{}".format(request.session['userGameActive']) + "_{}".format(iterator4)
                userAnswer = AnswerToTheQuizz.objects.get(usernamePlusQuestion = usernameComposed)

                answers = Answers.objects.get(answerId = userAnswer.goodAnswerId)

                score = Question.objects.get(question_id = 1)

                if (list_answers[iterator4] == answers.answer):
                    list_answer_to_answer.append("TrueQuestion")
                    gainedScore += score.points
                    
                
                else:
                    list_answer_to_answer.append("FalseQuestion")

                list_description_answer.append(answers.definition)
            
            user.score += gainedScore
            user.save()
            request.session['gainedScore'] = gainedScore

            request.session['list_answer_to_answer'] = list_answer_to_answer
            request.session['list_description_answer'] = list_description_answer 

            return redirect('QuizzMicroscopyCorrection')
            
        
        else:
            print(form.errors)



''' Method: MicroscopyQuizzView
    This method is used to redirect the user on the page 
    displaying the answers of the questions concerning 
    Microscopy'''


def MicroscopyQuizzPageCorrection(request):

    score = UserDatabase.objects.get(username=request.user.username)
    score = score.score

    return render(request, "quizzTemplate/quizzTemplateAnswers.html", 
        {'dictionnaryURL': request.session.get('dictionnaryURL'), 
        'list_answer_to_answer': request.session.get('list_answer_to_answer'), 
         'list_description_answer': request.session.get('list_description_answer'), 
         'list_choices': [('fluorescence microscopy', 0),  ('scanning electron microscopy (SEM)', 1), 
          ('transmission electron microscopy (TEM)', 2), ('phase contrast microscopy', 3)], 
          'list_answers': request.session.get('list_answers'), 'gained_score': request.session.get('gainedScore'), 
          'score': score})




''' Class: CellularComponentQuizzView
    This class is used to give the view of the page 
    displaying the questions concerning Cellular Component'''


class CellularComponentQuizzView(View):
    form = QuizzFormComponent

    def get(self,request):
    
        score = UserDatabase.objects.get(username=request.user.username)
        score = score.score

Webpage/MicroscopyQuizz/templates/quizzTemplate/quizzChoicesTemplate.html
{% extends 'base/baseForLogined.html' %}
{% load static %}

{% block content %}

<div class="home-title">What Type Of Question Do You Want Answer ?</div>
<a href="{% url 'QuizzMicroscopy' %}"><img src ="{% static "images/microscopy-optical_pic1.jpg" %}" class=pictureMicroscopyChoice></a>
<a href="{% url 'QuizzComponent' %}"><img src="{% static "images/halacious-OgvqXGL7XO4-unsplash.jpg"%}" class=pictureCellularComponentChoice></a>
<div class=textPictureMicroscopyChoice>Microscopy</div>
<div class=textCellularComponentChoice>Cellular Component</div>

{% endblock content%}

Webpage/MicroscopyQuizz/templates/quizzTemplate/quizzTemplateAnswers.html
{% extends 'base/baseForQuizz.html' %}
{% load static %}

{% block extrahead %}

    <script src="{% static "JS/jquery/jquery-3.5.1.min.js" %}"></script>
	<script src="{% static "JS/modifingLogin.js" %}"></script>
    <script type="text/javascript" src="{% static "JS/QuizzAnswers.js" %}"></script>

{% endblock %}

{% block content %}


<div class="home-title">You won {{ gained_score }} points</div>

    <table name="tableAnswers">

        {% for i, j in dictionnaryURL.items%}
        
            {% if i == 0%}

            <tr>
            <td>

                <div class = "firstQuestion" name="{{ list_answer_to_answer.0 }}">

                    <img src="{{ j.0 }}" id="img_0_{{ i }}">
                    <img src="{{ j.1 }}" id="img_1_{{ i }}">

                    <ul id="id_firstQuestion">

                    {% for k in list_choices %}

                        {% if k.0 == list_answers.0 %}
                            <li><label for="id_firstQuestion_{{ k.1 }}"><input type="radio" name="firstQuestion" value="{{ k.0 }}" checked>{{ k.0 }}</label></li>
                    
                        {% else %}
                            <li><label for="id_firstQuestion_{{ k.1 }}"><input type="radio" name="firstQuestion" value="{{ k.0 }}">{{ k.0 }}</label></li>

                        {% endif %}

                    {% endfor %}

                    </ul>

                    {% if list_answer_to_answer.0 == "TrueQuestion"%}
                        <p id="question1Answer">Good Answer!</p>

                    {% else %}
                        <p id="question1Answer">Bad Answer !</p>


                    {% endif %}


                    <p id="descriptionQuestion1">{{ list_description_answer.0 }}</p>


                </div>

            </td>
            </tr>

            {% endif %}

            {% if i == 1%}
            <tr>
            <td>

                <div class = "secondQuestion" name="{{ list_answer_to_answer.1 }}">

                    <img src="{{ j.0 }}" id="img_0_{{ i }}">
                    <img src="{{ j.1 }}" id="img_1_{{ i }}">

                    <ul id="id_secondQuestion">

                    {% for k in list_choices %}

                        {% if k.0 == list_answers.1 %}
                            <li><label for="id_secondQuestion_{{ k.1 }}"><input type="radio" name="secondQuestion" value="{{ k.0 }}" checked>{{ k.0 }}</label></li>
                    
                        {% else %}
                            <li><label for="id_firstQuestion_{{ k.1 }}"><input type="radio" name="secondQuestion" value="{{ k.0 }}">{{ k.0 }}</label></li>

                        {% endif %}

                    {% endfor %}

                    </ul>

                    {% if list_answer_to_answer.1 == "TrueQuestion"%}
                        <p id="question2Answer">Good Answer!</p>

                    {% else %}
                        <p id="question2Answer">Bad Answer !</p>

                    {% endif %}

                    <p id="descriptionQuestion2">{{ list_description_answer.1 }}</p>

               

                </div>

            </td>
            </tr>

            {% endif %}

            {% if i == 2 %}
            <tr>
            <td>

                <div class = "thirdQuestion" name="{{ list_answer_to_answer.2 }}">

                    <img src="{{ j.0 }}" id="img_0_{{ i }}">
                    <img src="{{ j.1 }}" id="img_1_{{ i }}">

                    <ul id="id_thirdQuestion">

                    {% for k in list_choices %}

                        {% if k.0 == list_answers.2 %}
                            <li><label for="id_thirdQuestion_{{ k.1 }}"><input type="radio" name="thirdQuestion" value="{{ k.0 }}" checked>{{ k.0 }}</label></li>
                    
                        {% else %}
                            <li><label for="id_thirdQuestion_{{ k.1 }}"><input type="radio" name="thirdQuestion" value="{{ k.0 }}">{{ k.0 }}</label></li>

                        {% endif %}

                    {% endfor %}

                    </ul>

                    {% if list_answer_to_answer.2 == "TrueQuestion"%}
                        <p id="question3Answer">Good Answer!</p>

                    {% else %}
                        <p id="question3Answer">Bad Answer !</p>

                    {% endif %}

                    <p id="descriptionQuestion3">{{ list_description_answer.2 }}</p>

               


                </div>

            </td>
            </tr>

            {% endif %}


            {% if i == 3 %}
             <tr>
             <td>
                <div class = "fourthQuestion" name="{{ list_answer_to_answer.3 }}">

                    <img src="{{ j.0 }}" id="img_0_{{ i }}">
                    <img src="{{ j.1 }}" id="img_1_{{ i }}">

                    <ul id="id_fourthQuestion">

                    {% for k in list_choices %}

                        {% if k.0 == list_answers.3 %}
                    
                            <li><label for="id_fourthQuestion_{{ k.1 }}"><input type="radio" name="fourthQuestion" value="{{ k.0 }}" checked>{{ k.0 }}</label></li>
                    
                        {% else %}
                            <li><label for="id_fourthQuestion_{{ k.1 }}"><input type="radio" name="fourthQuestion" value="{{ k.0 }}">{{ k.0 }}</label></li>

                        {% endif %}

                    {% endfor %}

                    </ul>

                    {% if list_answer_to_answer.3 == "TrueQuestion"%}
                        <p id="question4Answer">Good Answer!</p>

                    {% else %}
                        <p id="question4Answer">Bad Answer !</p>

                    {% endif %}

                    <p id="descriptionQuestion4">{{ list_description_answer.3 }}</p>

                

                </div>
            </td>
            </tr>
            {% endif %}


        {% endfor %}
        <tr>
        <td>
        <button id="buttonReturn" onclick="location.href = '{% url 'SignedIn' %}';">Save</button>
        </td>
        </tr>
    </table>

{% endblock content %}

Webpage/MicroscopyQuizz/templates/quizzTemplate/quizzTemplateAnswersMicroscopy.html
{% extends 'base/baseForQuizz.html' %}
{% load static %}

{% block extrahead %}

    <script src="{% static "JS/jquery/jquery-3.5.1.min.js" %}"></script>
	<script src="{% static "JS/modifingLogin.js" %}"></script>
    <script type="text/javascript" src="{% static "JS/QuizzAnswers.js" %}"></script>

{% endblock %}

{% block content %}


<div class="home-title">You won {{ gained_score }} points</div>

    <table name="tableAnswers">

        {% for i, j in dictionnaryURL.items%}
        
            {% if i == 0%}

            <tr>
            <td>

                <div class = "firstQuestion" name="{{ list_answer_to_answer.0 }}">

                    <img src="{{ j.0 }}" id="img_0_{{ i }}">
                    <img src="{{ j.1 }}" id="img_1_{{ i }}">

                    <ul id="id_firstQuestion">

                    {% for k in list_choices %}

                        {% if k.0 == list_answers.0 %}
                            <li><label for="id_firstQuestion_{{ k.1 }}"><input type="radio" name="firstQuestion" value="{{ k.0 }}" checked>{{ k.0 }}</label></li>
                    
                        {% else %}
                            <li><label for="id_firstQuestion_{{ k.1 }}"><input type="radio" name="firstQuestion" value="{{ k.0 }}">{{ k.0 }}</label></li>

                        {% endif %}

                    {% endfor %}

                    </ul>

                    {% if list_answer_to_answer.0 == "TrueQuestion"%}
                        <p id="question1Answer">Good Answer!</p>

                    {% else %}
                        <p id="question1Answer">Bad Answer !</p>


                    {% endif %}


                    <p id="descriptionQuestion1">{{ list_description_answer.0 }}</p>


                </div>

            </td>
            </tr>

            {% endif %}

            {% if i == 1%}
            <tr>
            <td>

                <div class = "secondQuestion" name="{{ list_answer_to_answer.1 }}">

                    <img src="{{ j.0 }}" id="img_0_{{ i }}">
                    <img src="{{ j.1 }}" id="img_1_{{ i }}">

                    <ul id="id_secondQuestion">

                    {% for k in list_choices %}

                        {% if k.0 == list_answers.1 %}
                            <li><label for="id_secondQuestion_{{ k.1 }}"><input type="radio" name="secondQuestion" value="{{ k.0 }}" checked>{{ k.0 }}</label></li>
                    
                        {% else %}
                            <li><label for="id_firstQuestion_{{ k.1 }}"><input type="radio" name="secondQuestion" value="{{ k.0 }}">{{ k.0 }}</label></li>

                        {% endif %}

                    {% endfor %}

                    </ul>

                    {% if list_answer_to_answer.1 == "TrueQuestion"%}
                        <p id="question2Answer">Good Answer!</p>

                    {% else %}
                        <p id="question2Answer">Bad Answer !</p>

                    {% endif %}

                    <p id="descriptionQuestion2">{{ list_description_answer.1 }}</p>

               

                </div>

            </td>
            </tr>

            {% endif %}

            {% if i == 2 %}
            <tr>
            <td>

                <div class = "thirdQuestion" name="{{ list_answer_to_answer.2 }}">

                    <img src="{{ j.0 }}" id="img_0_{{ i }}">
                    <img src="{{ j.1 }}" id="img_1_{{ i }}">

                    <ul id="id_thirdQuestion">

                    {% for k in list_choices %}

                        {% if k.0 == list_answers.2 %}
                            <li><label for="id_thirdQuestion_{{ k.1 }}"><input type="radio" name="thirdQuestion" value="{{ k.0 }}" checked>{{ k.0 }}</label></li>
                    
                        {% else %}
                            <li><label for="id_thirdQuestion_{{ k.1 }}"><input type="radio" name="thirdQuestion" value="{{ k.0 }}">{{ k.0 }}</label></li>

                        {% endif %}

                    {% endfor %}

                    </ul>

                    {% if list_answer_to_answer.2 == "TrueQuestion"%}
                        <p id="question3Answer">Good Answer!</p>

                    {% else %}
                        <p id="question3Answer">Bad Answer !</p>

                    {% endif %}

                    <p id="descriptionQuestion3">{{ list_description_answer.2 }}</p>

               


                </div>

            </td>
            </tr>

            {% endif %}


            {% if i == 3 %}
             <tr>
             <td>
                <div class = "fourthQuestion" name="{{ list_answer_to_answer.3 }}">

                    <img src="{{ j.0 }}" id="img_0_{{ i }}">
                    <img src="{{ j.1 }}" id="img_1_{{ i }}">

                    <ul id="id_fourthQuestion">

                    {% for k in list_choices %}

                        {% if k.0 == list_answers.3 %}
                    
                            <li><label for="id_fourthQuestion_{{ k.1 }}"><input type="radio" name="fourthQuestion" value="{{ k.0 }}" checked>{{ k.0 }}</label></li>
                    
                        {% else %}
                            <li><label for="id_fourthQuestion_{{ k.1 }}"><input type="radio" name="fourthQuestion" value="{{ k.0 }}">{{ k.0 }}</label></li>

                        {% endif %}

                    {% endfor %}

                    </ul>

                    {% if list_answer_to_answer.3 == "TrueQuestion"%}
                        <p id="question4Answer">Good Answer!</p>

                    {% else %}
                        <p id="question4Answer">Bad Answer !</p>

                    {% endif %}

                    <p id="descriptionQuestion4">{{ list_description_answer.3 }}</p>

                

                </div>
            </td>
            </tr>
            {% endif %}


        {% endfor %}
        <tr>
        <td>
        <button id="buttonReturn" onclick="location.href = '{% url 'SignedIn' %}';">Save</button>
        </td>
        </tr>
    </table>

{% endblock content %}